use_default_settings: true

server:
  secret_key: "YOUR_UNIQUE_SECRET_KEY_CHANGE_ME"
  limiter: false
  bind_address: "0.0.0.0:7860"   # Force port 7860

search:
  formats:
    - json
  disabled_engines:
    - google
    - google_images
    - google_news
    - google_videos
    - duckduckgo
    - brave
    - startpage
    - karmasearch
    - ahmia
    - torch
    - radio_browser
    - bing
  enabled_engines:
    - qwant
    - mojeek
    - stract
    - wikipedia
    - yahoo
