use_default_settings: true

server:
  secret_key: "YOUR_UNIQUE_SECRET_KEY_CHANGE_ME"
  limiter: false

search:
  formats:
    - json
  disabled_engines:
    - google
    - google_images
    - google_news
    - google_videos
    - duckduckgo
    - brave
    - startpage
    - karmasearch
    - ahmia
    - torch
    - radio_browser
    - bing               # Bing also might block, remove if needed
  enabled_engines:
    - qwant
    - mojeek
    - stract            # still keep stract in SearXNG as fallback
    - wikipedia
    - yahoo
